name: "Finger deploy"

on:
  pull_request:
    types: [labeled]

jobs:
  validate-code:
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: echo 'Running the linter...'
  deploy-dev:
    if: ${{ github.event.label.name == 'finger deploy' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploying to development
        run: echo 'Hello, world!'
